spring.application.name=fitness-performance-tracker

spring.datasource.url=jdbc:mysql://localhost:3306/fitness-performance-tracker?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true